Se agrega build

diff --git a/build/prerrequisites.yml b/build/prerrequisites.yml
--- a/build/prerrequisites.yml
+++ b/build/prerrequisites.yml
@@ -13,20 +13,22 @@ phases:
       - echo "Configuring AWS CLI for multi-account role assumption"
       - BRANCH_NAME=$(echo $CODEBUILD_SOURCE_VERSION | sed 's|refs/heads/||')
       
-      - case "$BRANCH_NAME" in
+      - |
+        case "$BRANCH_NAME" in
           prod) AWS_ROLE_ARN="arn:aws:iam::PROD_ACCOUNT_ID:role/ProdRole" ;;
           qa) AWS_ROLE_ARN="arn:aws:iam::QA_ACCOUNT_ID:role/QARole" ;;
           dev) AWS_ROLE_ARN="arn:aws:iam::699631259047:role/TerraformDeploymentRole" ;;
           dr) AWS_ROLE_ARN="arn:aws:iam::DR_ACCOUNT_ID:role/DRRole" ;;
-          *) echo "Unknown branch $BRANCH_NAME" && exit 1 ;;
+          *) echo "Unknown branch: $BRANCH_NAME" && exit 1 ;;
         esac
 
       - echo "Assuming role: $AWS_ROLE_ARN"
       - ROLE_SESSION_NAME="CodeBuildSession"
-      - CREDENTIALS=$(aws sts assume-role --role-arn "$AWS_ROLE_ARN" --role-session-name "$ROLE_SESSION_NAME" --output json) || { echo "Failed to assume role"; exit 1; }
-      - export AWS_ACCESS_KEY_ID=$(echo "$CREDENTIALS" | jq -r '.Credentials.AccessKeyId')
-      - export AWS_SECRET_ACCESS_KEY=$(echo "$CREDENTIALS" | jq -r '.Credentials.SecretAccessKey')
-      - export AWS_SESSION_TOKEN=$(echo "$CREDENTIALS" | jq -r '.Credentials.SessionToken')
+      - |
+        CREDENTIALS=$(aws sts assume-role --role-arn "$AWS_ROLE_ARN" --role-session-name "$ROLE_SESSION_NAME" --output json) || { echo "Failed to assume role"; exit 1; }
+        export AWS_ACCESS_KEY_ID=$(echo "$CREDENTIALS" | jq -r '.Credentials.AccessKeyId')
+        export AWS_SECRET_ACCESS_KEY=$(echo "$CREDENTIALS" | jq -r '.Credentials.SecretAccessKey')
+        export AWS_SESSION_TOKEN=$(echo "$CREDENTIALS" | jq -r '.Credentials.SessionToken')
 
   build:
     commands:
@@ -36,7 +38,8 @@ phases:
       - echo "Current directory: $(pwd)"
       - echo "Listing files:" && ls -a
 
-      - case "$BRANCH_NAME" in
+      - |
+        case "$BRANCH_NAME" in
           prod) cp ./environments/prod/terraform.tfvars terraform.tfvars ;;
           qa) cp ./environments/qa/terraform.tfvars terraform.tfvars ;;
           dev) cp ./environments/dev/terraform.tfvars terraform.tfvars ;;
